### ISSUE TITLE
A Friendly Invitation

### ISSUE THREAD

**Issue by ApolloZhu** [mayongl/CS193p_Subs#1]
Hi, Yonglin Ma.

I think you have the same interest as me and the rest of us. Please have a look at https://github.com/ApolloZhu/Developing-iOS-10-Apps-with-Swift. We've already made some progress on the translation. We are also looking for more kind-hearted people like you.

Your cooperation and help are highly appreciated. Thank you in advance for contributing to the Swift and the Chinese developer community.

**Comment by mayongl** [comment]
Get it. Thanks for the invitation.
